// File generated by FlutterFire CLI.
// Run: flutterfire configure
// Then replace this file with the generated one.
//
// SETUP STEPS:
// 1. Go to https://console.firebase.google.com and create a project
// 2. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
// 3. From this project root run: flutterfire configure
// 4. Select your Firebase project and platforms (Android, iOS, Web)
// 5. This file will be auto-generated with your real config values.
//
// Until then, the placeholder values below will cause Firebase to fail at runtime.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDqH-uKV8cTkLeC3MRftMP9mt6PVWYa64',
    appId: '1:724973894398:android:e98d4ba423a2ce254fc3af',
    messagingSenderId: '724973894398',
    projectId: 'adam-58d69',
    storageBucket: 'adam-58d69.firebasestorage.app',
  );

  // TODO: Replace with your real Firebase config from: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGo6q8qIhwn8h5V2I_y-rtCNLVBqFSitk',
    appId: '1:724973894398:ios:a462930922ab11564fc3af',
    messagingSenderId: '724973894398',
    projectId: 'adam-58d69',
    storageBucket: 'adam-58d69.firebasestorage.app',
    iosBundleId: 'com.example.aiVoiceChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.aiVoiceChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}